name: CI/CD

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm ci

            # - name: Build app
            #   run: npm run build

            - name: Deploy app
              uses: easingthemes/ssh-deploy@v2.1.8
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                  ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
                  remote-user: username
                  server-ip: server_ip
                  local-folder: src/
                  remote-folder: /home/phones/myapp
                  post-deploy: "pm2 reload ecosystem.config.js --env production"
