name: test-cicd

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run build --if-present
            # - run: npm test
            - run: tar -czvf api-bundle.tar.gz build node_modules package.json ecosystem.config.js

            - name: Push to the dock
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  source: "./api-bundle.tar.gz"
                  target: "/home/phones/app/my-app/"

            - name: Compose build file on server
              uses: fifsky/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  user: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  command: |
                      tar -xzf /home/me/app/my-app/api-bundle.tar.gz -C /home/me/app/my-app/
                      pm2 start pm2.config.ts
